monero-rs/monero-rs

- .travis.yml
- Cargo.toml
- README.md
> Add CI for wasm and remove default features

- Cargo.toml
- src/blockdata/block.rs
- src/blockdata/transaction.rs
- src/consensus/encode.rs
- src/cryptonote/hash.rs
- src/util/address.rs
- src/util/key.rs
- src/util/ringct.rs
Added support for serde across the board. This is hidden behind a feature flag serde_support. The old serde flag will still work and still only work for the address struct. 
Added Debug, Clone and Default derives to most structs as well. This will make it easier to integrate with code that requires those.
> Add better serde support as well as defualt, clone and debug derive flags

- Cargo.toml
Updated dalek dependancy
locked serde and dalek to a finer version.
It looks like the newer rust version breaks with serde isnt upgraded. This fixes it.
> Updated dependancies

- Cargo.toml
- src/blockdata/transaction.rs
- src/lib.rs
- src/network.rs
- src/util/address.rs
- src/util/key.rs
- src/util/mod.rs
Error trait from the standard library has been deprecated.
Failure is the de-facto replacement. Derives `Fail` trait for all
internal error types.
> Replace std::error::Error trait with Failure crate

- Cargo.toml
- src/lib.rs
- src/network.rs
- src/util/address.rs
- src/util/key.rs
- src/util/mod.rs
Greetings @h4sh3d !
This commit removes the deprecated `failure` crate in favour of `thiserror` - fixes #19  
Tests pass successfully, but please let me know if it doesn't work as intended!
> Replace deprecated failure crate with thiserror

- src/blockdata/block.rs
- src/blockdata/transaction.rs
- src/consensus/encode.rs
- src/util/ringct.rs
I implemented display for most of the struct. 
I know too little of monero to know what is actually good info to display. So I tried to balance it out what I think would be good info. 
This will now allow a user to call `println!("block: {}", block);` and it should display it in an ergonomical fashion.
> Implement display for most stucts

- src/util/key.rs
- src/util/ringct.rs
These are useful when trying to write code that is generic over constructing / deserializing things from byte slices and arrays.
I wasn't quite sure how invasive I should be in terms of the derives (most of the types in the `ringct` module could probably use a couple of derives) so I only added the ones that I need at the moment.
> Add several trait implementations for `PrivateKey`, `PublicKey` and `ringct::{Key, Key64}`

- Cargo.toml
- src/cryptonote/hash.rs
- src/util/address.rs
The dependency footprint of tiny-keccak is smaller and it also has
a more versatile API that allows streaming bytes into the hash
engine.
Before:
❯ cargo tree | wc -l
56
After:
❯ cargo tree | wc -l
48
> Replace keccak-hash with tiny-keccak

- src/blockdata/transaction.rs
- src/util/amount.rs
- src/util/mod.rs
- src/util/ringct.rs
- tests/recover_outputs.rs
The first 4 patches are refactorings.
The last one adds the actual functionality.
If the signatures are present in the transaction struct, we unblind and extract all possible information for a specific output. We will need this functionality once we upstream bulletproof and clsag functionality.
> Expose all confidential information of output through `OwnedTxOut`

- Cargo.toml
- src/blockdata/transaction.rs
~Includes https://github.com/monero-rs/monero-rs/pull/40 until merged, hence draft for now.~
~What do you think is the best way to test this?
The original implementation is [here](https://github.com/monero-project/monero/blob/dcba757dd283a3396120f0df90fe746e3ec02292/src/ringct/rctSigs.cpp#L573-L631) but it doesn't include any unit tests (presumably because constructing a TX is quite the effort and half the transaction is hashed here ...)~
~We can add tests that "freeze" the current implementation but that might be as good as it gets.~
Once we upstream the full CLSAG implementation, it might be easier because we can take mainnet transactions and verify their signature which includes producing the correct message hash.
TODO:
> Add function for computing the signature hash of a transaction

- src/blockdata/transaction.rs
- src/consensus/encode.rs
- Add bound check in `Decodable` impl for `Vec`
- This fixes the same issue for `Decodable` impl on `String`
- Add unit tests for `Vec` and `String` deserialisation, incl panic/OOM case 
Fixes #46
> Add length bounds check before allocating Vec (Fixes #46)

- src/blockdata/transaction.rs
Implementations of `Encodable` should never fail unless the underlying
encoder fails. The implementation of `io::Write` for `Vec<u8>` is
easier to audit for this invariant than `io::Cursor`. Use `Vec<u8>`
instead of `io::Cursor`.
Found while reviewing https://github.com/monero-rs/monero-rs/pull/48.
> Don't use io::Cursor for implementing `Encodable` on `ExtraField`

- Cargo.toml
Fix #51 
Enable the serde feature on curve25519-dalek only when crate's feature serde_support is enabled.
> Fix activation of curve25519-dalek's feature serde

- Cargo.toml
- src/blockdata/transaction.rs
- src/consensus/encode.rs
- src/cryptonote/hash.rs
- src/internal_macros.rs
- src/util/key.rs
- src/util/ringct.rs
@sdbondi @thomaseizinger 
As discussed in #48, this fix `Encodable` for `TxIn`, removing the failures caused by the unused variants for scripts.
The deserialization is allowed to fail, so I kept this line in `Decodable` for `TxIn`, but we can also remove it if it makes more sense, feel free to push on top of this.
```rust
0x0 | 0x1 => Err(Error::ScriptNotSupported.into()),
...
_ => Err(encode::Error::ParseFailed("Invalid input type")),
```
> Remove unused TxIn variants and seal Encodable

- src/blockdata/transaction.rs
- src/cryptonote/hash.rs
- src/util/key.rs
- src/util/ringct.rs
Rename `hash` method into `new` to avoid repeating the name of the type. Change `null_hash` into `null`. Relax input type for creating hash with `AsRef<[u8]>` instead of `&[u8]`.
> Modify Hash public API

- CHANGELOG.md
- Cargo.toml
Waiting on review for #59 and #60.
Prepare release of `0.15.0`, version is bumped because #59 breaks the current API.
> Prepare release 0.15.0

- .github/workflows/ci.yml
- .github/workflows/create-release.yml
- .github/workflows/draft-new-release.yml
- .github/workflows/release-to-crates-io.yml
- CHANGELOG.md
- Cargo.toml
- README.md
- RELEASING.md
- dprint.json
Add workflows to automate release management, workflows are based on `monero-rs/workflows`.
Added `dprint` in CI and ran `dprint fmt` on the code base.
> Release automation

- CHANGELOG.md
- Cargo.toml
- src/util/amount.rs
- tests/serde.rs
Mimics the amount serde implementation of rust-bitcoin.
Due to precision concerns, XMR amounts are serialized as strings. @h4sh3d  let me know if there is a better alternative instead of using strings. 
Rustc emitted a false positive dead code warning for the `serialize` and `deserialize` impls. Do you maybe have an idea what is going on there @h4sh3d ?
> Amount: Add serde support

- CHANGELOG.md
- Cargo.toml
Bump `base58-monero` requirement to `"1"`.
> chore: update base58 to version 1

- .github/codecov.yml
Same config as base58-monero repo.
> chore: add codecov config

- CHANGELOG.md
- src/blockdata/transaction.rs
- tests/blockdata.rs
- tests/data/block.json
- tests/recover_outputs.rs
Fix #83
On coinbase transactions the amount is in clear with a `RctType::Null`, this PR fixes the logic to handle that case. Data for `check_output_on_miner_tx` test has been generated with monerod and monero-wallet-cli in regtest mode.
> fix: check outputs of miner transaction

- src/util/amount.rs
clippy complains about signed into unsigned cast. `usize` is still required to transform `u32` into `usize` for later computation.
> fix: clippy cast warning

- src/blockdata/transaction.rs
- src/consensus/encode.rs
- src/cryptonote/hash.rs
- src/internal_macros.rs
- src/util/address.rs
- src/util/key.rs
- src/util/ringct.rs
Needs #103 for CI to pass
While doing `strict_encoding` integration of Monero I made some small changes on the `consensus` module.
> feat: consensus en/decoding support unsized `R` and `W`

- CHANGELOG.md
I wasn't sure about #101 if it should be part of the changelog or not, but I guess event if it doesn't concern the public API directly it good to track that change too. So I open this one to update the changelog before releasing 0.17.1.
> chore: update changelog for 0.17.1

- CHANGELOG.md
- src/blockdata/transaction.rs
- src/util/ringct.rs
- tests/recover_outputs.rs
Closes #98 
Those are the places where it seemed to make sense to change to `Amount`. Some other places use `VarInt`, but unsure if it makes sense to change to `Amount`.
Also, `fn parse_signed_to_piconero` in `amount.rs` returns `Result<(bool, u64), ParsingError>`, but it is an internal function used inside `Amount` and `SignedAmount` methods.
I did not find any places using `i64` where a `SignedAmount` could be used.
> refactor: use `Amount` where it makes sense instead of u64 or VarInt

- CHANGELOG.md
- src/cryptonote/hash.rs
- src/util/address.rs
Closes #108
Implements `FromHex` for `Hash`, `Hash8`, and `PaymentId`.
Implements `ToHex` and `FromHex` for `Address`. Note that it has similar methods: `as_hex` and `from_bytes`.
Note that `Hash`, `Hash8`, and `PaymentId` implement `FromStr` from here https://docs.rs/fixed-hash/latest/src/fixed_hash/hash.rs.html#577
> Add FromHex for Hash, Hash8, PaymentId and Address; add ToHex for Address

- src/blockdata/transaction.rs
- tests/blockdata.rs
Extra data is not really part of consensus so unparseable extra data transactions exist and are valid.
Resolves #135
> Erased type of extra data

- CHANGELOG.md
- src/util/amount.rs
Relax parsing denomination: before only `XMR`, now `xmr`, `XMR`, `monero`. Prefer lower case in `Display`: `1 XMR` is now `1 xmr`.
**NOTE: this patch has been ported and released under `v0.17.3` too!**
> Feat: allow more denomination variants

- CHANGELOG.md
- src/blockdata/transaction.rs
only miner txs are effected as normal txs must have 16 or less outs.
https://github.com/monero-project/monero/blob/ac02af92867590ca80b2779a7bbeafa99ff94dcb/src/crypto/crypto.cpp#L765
> fix transaction scanning for txs with view tags and lots of outputs

- CHANGELOG.md
- Cargo.toml
- src/blockdata/transaction.rs
- src/util/fuzz_utils.rs
Fixed merge mining tag depth encoding and decoding to be in line with https://github.com/monero-project/monero.
~~A feature flag `merge_mining_field_upgrade_v0_18` is added to prepare for the next monero release, as the merge mining subfield encoding has been changed on the monero `master`, but not yet released. In this way, the library can be compiled for the current official release or latest development.~~
[master @ 2024-03-19, cryptonote_format_utils.cpp#L742](https://github.com/monero-project/monero/blob/c8214782fb2a769c57382a999eaf099691c836e7/src/cryptonote_basic/cryptonote_format_utils.cpp#L742)
~~[release-v0.18, cryptonote_format_utils.cpp#L742](https://github.com/monero-project/monero/blob/release-v0.18/src/cryptonote_basic/cryptonote_format_utils.cpp#L726)~~
> feat: fix merge mining field depth
