Cargo.toml
=> Move fixed-hash/std and fixed-hash/rand into default features

src/blockdata/block.rs, src/consensus/encode.rs
=> add serialize deserialize test of block

src/blockdata/block.rs, src/blockdata/transaction.rs, src/consensus/encode.rs, src/util/address.rs
Reverted changes for PR #15
Modified test to better illustrate the issue.
=> Deserialization Issue

Cargo.toml
Luckily the breaking changes didn't affect this project.
=> Upgrade curve25519_dalek to 3.0

src/blockdata/transaction.rs, src/util/amount.rs, src/util/mod.rs
Small changes about error handling.
=> Impl this error and move amount recovery error

src/blockdata/transaction.rs
Fix match on option and use option map instead
=> Fix CI static analysis errors

CHANGELOG.md, Cargo.toml, LICENSE, README.md, src/blockdata/transaction.rs, src/consensus/encode.rs, src/util/address.rs
Prepare release of `0.14.0`
Add CHANGELOG and modify copyright in license to 'Monero Rust Contributors'
=> Prepare release 0.14.0

CHANGELOG.md, Cargo.toml
Fix formatting and link creation (GH does not autolink in files inside the repo). Add changelog in files included inside cargo release.
=> Improve changelog

README.md, src/lib.rs
Fix #55 
Add paragraph in README and Rust Doc.
=> Document experimental feature

.github/workflows/ci.yml, README.md
Test building the lib with the MSRV found by `cargo msrv --bisect` command in CI.
=> Add MSRV badge in README

src/blockdata/transaction.rs
The current `check_outputs()` method generates the `SubKeyChecker` table each time it is called, which can be slow if the table is large. When performance is a priority, it would be nice to have a method that accepts an existing `SubKeyChecker` as input. 
The implementation in this PR is the least-invasive way I could see to make the addition, but there are are many ways to skin this cat. If you guys have a preferred way to accomplish this, just say the word and I'll give it a shot.
=> Add method to check outputs with existing SubKeyChecker.

CHANGELOG.md, src/cryptonote/subaddress.rs
=> Update changelog with #64

.github/workflows/ci.yml, .github/workflows/create-release.yml
Update steps in CI, cover building with all feature combinations.
=> Minor CI update

src/cryptonote/subaddress.rs
This should fix CI static analysis.
=> Use derive Default for Index

.github/workflows/create-release.yml, .github/workflows/draft-new-release.yml, .github/workflows/release-to-crates-io.yml
Bump shared workflow to latest version, no breaking changes expected.
=> chore: bump shared workflow to v2

dprint.json
Bump dprint markdown and toml plugins.
=> chore: update dprint plugins

LICENSE, src/blockdata/block.rs, src/blockdata/mod.rs, src/blockdata/transaction.rs, src/consensus/encode.rs, src/consensus/mod.rs, src/cryptonote/hash.rs, src/cryptonote/mod.rs, src/cryptonote/onetime_key.rs, src/cryptonote/subaddress.rs, src/internal_macros.rs, src/lib.rs, src/network.rs, src/util/address.rs, src/util/amount.rs, src/util/key.rs, src/util/mod.rs, src/util/ringct.rs, tests/blockdata.rs, tests/recover_outputs.rs, tests/serde.rs
Update copyright to Monero Rust Contributors and update years.
=> chore: update headers

.github/workflows/ci.yml, CHANGELOG.md, Cargo.toml, README.md, src/blockdata/block.rs, src/blockdata/transaction.rs, src/consensus/encode.rs, src/cryptonote/hash.rs, src/lib.rs, src/util/address.rs, src/util/amount.rs, src/util/key.rs, src/util/ringct.rs, tests/serde.rs
=> refactor: rename feature serde_support into serde

CHANGELOG.md, src/cryptonote/subaddress.rs
This is needed for https://github.com/monero-ecosystem/monero-rpc-rs/issues/41
=> feat(subaddress): add Serialize and Deserialize for SubAddress Index

CHANGELOG.md, src/cryptonote/hash.rs, src/util/amount.rs
This is going to be needed for https://github.com/monero-ecosystem/monero-rpc-rs/pull/68
Check changelog and tests to see the changes :)
=> Add serialization for slices of Amount and SignedAmount, and Deserialization into Vec<Amount> and Vec<SignedAmount>

CHANGELOG.md
Add more author names on changes. Simplify #107 changelog to only two lines.
=> chore: rework changelog

CHANGELOG.md, src/blockdata/transaction.rs
fixes #122 
I have made it so de-serialization of the extra field will always return the raw extra field and it will try to parse it, instead of failing if it cannot be parsed.
=> Fix extra field

src/lib.rs
just fixed a typo on the documentation
=> fixed a typo

.github/workflows/ci.yml, .github/workflows/coverage.yml, Cargo.toml, LICENSE, README.md, src/blockdata/block.rs, src/blockdata/mod.rs, src/blockdata/transaction.rs, src/consensus/encode.rs, src/consensus/mod.rs, src/cryptonote/hash.rs, src/cryptonote/mod.rs, src/cryptonote/onetime_key.rs, src/cryptonote/subaddress.rs, src/internal_macros.rs, src/lib.rs, src/network.rs, src/util/address.rs, src/util/amount.rs, src/util/key.rs, src/util/mod.rs, src/util/ringct.rs, tests/blockdata.rs, tests/recover_outputs.rs, tests/serde.rs
Chore to update what needs to be updated before merging pending PRs
=> Chore: update deps & ci

src/util/amount.rs, src/util/ringct.rs
Make sure copy/paste work in external project
=> Doc: improve serde amount modules

CHANGELOG.md, src/blockdata/block.rs, src/cryptonote/hash.rs, src/util/address.rs
This fixes the bug in issue #188
=> fix: Do not prepend VarInt len to Block::serialize_hashable()

CHANGELOG.md, src/util/address.rs
Fixed out of bounds panics in `src/util/address.rs` for `from_bytes` and `from_slice`
=> feat: fix out-of-bounds address panics

CHANGELOG.md, fuzz/fuzz_targets/raw_extra_field_d.rs, fuzz/fuzz_targets/transaction_check_outputs.rs, fuzz/fuzz_targets/transaction_hash.rs, src/blockdata/block.rs, src/blockdata/transaction.rs, src/consensus/encode.rs, src/util/fuzz_utils.rs, src/util/ringct.rs, tests/recover_outputs.rs
- Fixed memory overflow - covered by unit tests `previous_fuzz_block_deserialize_failures` and `previous_fuzz_transaction_deserialize_failures1`.
- Fixed subtract with overflow - covered by unit test `previous_fuzz_transaction_deserialize_failures2`.
**Note:** #186 must be merged first
=> feat: fix memory overflow

src/blockdata/transaction.rs
=> remove unused enum variant
